infrastructure.directory.authorizationmanagement.getcredentialsforpersonincludingprotectedperson.endpoint.url=${ntjp.base.url}/infrastructure/directory/authorizationmanagement/GetCredentialsForPersonIncludingProtectedPerson/2/rivtabp21
infrastructure.directory.authorizationmanagement.gethospcredentialsforperson.endpoint.url=${ntjp.base.url}/infrastructure/directory/authorizationmanagement/GetHospCredentialsForPerson/1/rivtabp21
infrastructure.directory.authorizationmanagement.gethosplastupdate.endpoint.url=${ntjp.base.url}/infrastructure/directory/authorizationmanagement/GetHospLastUpdate/1/rivtabp21
infrastructure.directory.authorizationmanagement.handlehospcertificationperson.endpoint.url=${ntjp.base.url}/infrastructure/directory/authorizationmanagement/HandleHospCertificationPerson/1/rivtabp21

infrastructure.directory.employee.getemployee.endpoint.url=${ntjp.base.url}/infrastructure/directory/employee/GetEmployeeIncludingProtectedPerson/2/rivtabp21

infrastructure.directory.organization.gethealthcareprovider.endpoint.url=${ntjp.base.url}/infrastructure/directory/organization/GetHealthCareProvider/1/rivtabp21
infrastructure.directory.organization.gethealthcareunit.endpoint.url=${ntjp.base.url}/infrastructure/directory/organization/GetHealthCareUnit/2/rivtabp21
infrastructure.directory.organization.gethealthcareunitmembers.endpoint.url=${ntjp.base.url}/infrastructure/directory/organization/GetHealthCareUnitMembers/2/rivtabp21
infrastructure.directory.organization.getunit.endpoint.url=${ntjp.base.url}/infrastructure/directory/organization/GetUnit/2/rivtabp21

hsa.unit.cache.expiry=86400
hsa.healthcareunit.cache.expiry=86400
hsa.healhcareunitmembers.cache.expiry=86400
hsa.employee.cache.expiry=60

app.name=noname
infrastructure.directory.logicalAddress=SE165565594230-1000

# TLS
ntjp.ws.certificate.file=dummy.p12
ntjp.ws.certificate.type=PKCS12
ntjp.ws.key.manager.password=password
ntjp.ws.certificate.password=password

ntjp.ws.truststore.file=dummy.jks
ntjp.ws.truststore.type=JKS
ntjp.ws.truststore.password=password


# Dynamic loading of identities into HSA stub
hsa.stub.additional.identities.folder=${java.io.tmpdir}