/*
 * Copyright (C) 2018 Inera AB (http://www.inera.se)
 *
 * This file is part of sklintyg (https://github.com/sklintyg).
 *
 * sklintyg is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * sklintyg is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.02.08 at 11:07:51 AM CET
//

@javax.xml.bind.annotation.XmlSchema
        (namespace = "http://www.w3.org/2000/09/xmldsig#",
                xmlns = {@XmlNs(prefix = "", namespaceURI = "http://www.w3.org/2000/09/xmldsig#")},
                elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)

package se.inera.intyg.infra.xmldsig.model;

import javax.xml.bind.annotation.XmlNs;
